using ZapretDesktop;
var start=DateTimeOffset.UtcNow;
var p=new RecoveryPolicy();int count=0;
void Check(string expected,int seconds,bool online=true,string network="a",bool running=true,bool busy=false,bool? healthy=null,bool resumed=false){
 var result=p.Observe(start.AddSeconds(seconds),online,network,running,busy,healthy,resumed);
 if(result.Kind!=expected)throw new Exception($"{count}: expected {expected}, got {result.Kind}");
 count++;
}
Check("none",0,running:false);
p.Arm("a",start);
Check("none",0);
Check("none",1,healthy:false);
Check("wait",2,healthy:false);
Check("wait",6);
Check("recover",7);
Check("wait",8,running:false);
Check("wait",26,running:false);
Check("recover",27,running:false);
Check("wait",28,running:false);
Check("recover",87,running:false);
Check("wait",88,running:false);
Check("limited",207,running:false);
Check("recover",607,running:false);
p.Disarm();Check("none",608,running:false,resumed:true);
p.Arm("a",start);
Check("wait",0,network:"b");
Check("wait",4,network:"b");
Check("recover",5,network:"b");
p.Arm("a",start);
Check("wait",0,online:false,running:false);
Check("wait",700,online:false,running:false);
Check("recover",701,running:false);
p.Arm("a",start);
Check("wait",0,resumed:true);
Check("none",5,busy:true);
Check("recover",6);
p.Arm("a",start);
Check("none",0,healthy:false);
Check("none",1,healthy:true);
Check("none",2,healthy:false);
Check("wait",3,running:false);
Check("recover",8,running:false);
Check("none",309,healthy:true);
Check("wait",310,running:false);
Check("recover",315,running:false);
Console.WriteLine($"TOTAL {count} recovery checks passed");
